/*
 *   initsubsystem - set the BSS segment to all zeros.
 */

extern char _edata;   /* these values are generated by the linker */
extern char _end;     /* see tools/ld-script.h */


void _M2_initsubsystem_init (void)
{
  char *p = (char *) &_edata;
  char *q = (char *) &_end;

  while (p < q) {
    *p = (char) 0;
    p++;
  }
}


/* does nothing */

void _M2_initsubsystem_finish (void) {}
