/* Header for module BufferDevice, generated by p2c */
#ifndef BufferDeviceH
#define BufferDeviceH


#ifdef BufferDeviceG
# define vextern
#else
# define vextern extern
#endif


/*
   Author      : Gaius Mulley
   Version     : 1.0
   Date        : 12/2/86
   Last Update : 2/8/86
   Description : Exports a general Read and Write Buffer procedure. Buffers
                 are dynamic.
*/


#ifndef BufferDeviceG
/* opaque type declaration */
typedef void *BufferDevice_Buffer;

#endif


/*
   InitBuffer - creates, and initializes, a buffer and returns it.
*/


extern void *(BufferDevice_InitBuffer(void));

/*
   KillBuffer - destroys the buffer and relinquishes all associated
                resources.
*/

extern void BufferDevice_KillBuffer(void **b);


/*
   ReadBuffer - reads a character, ch, from the buffer, b.
*/

extern void BufferDevice_ReadBuffer(void *b, Char *ch);


/*
   WriteBuffer - places a character, ch, into buffer, b.
*/

extern void BufferDevice_WriteBuffer(void *b, Char ch);


#undef vextern

#endif /*BufferDeviceH*/

/* End. */
