/* Header for module ColourText, generated by p2c */
#ifndef ColourTextH
#define ColourTextH


#ifdef ColourTextG
# define vextern
#else
# define vextern extern
#endif

/*
    Title      : ColourText
    Author     : Gaius Mulley
    System     : UNIX (gm2)
    Date       : Sun Jul 31 20:31:10 1994
    Last edit  : Sun Jul 31 20:31:10 1994
    Description: provides a simple interface to basic colour text.
*/



/*
   WriteCharacterAndAttribute - writes character, ch, to screen location,
                                x, y, with attibute colour, colour.
*/

extern void ColourText_WriteCharacterAndAttribute(unsigned int x,
  unsigned int y, Char ch, unsigned int colour);



#undef vextern

#endif /*ColourTextH*/

/* End. */
