/* Header for module Colours, generated by p2c */
#ifndef ColoursH
#define ColoursH


#ifdef ColoursG
# define vextern
#else
# define vextern extern
#endif




#define Colours_Black   0
#define Colours_Blue    1
#define Colours_Green   2
#define Colours_Cyan    3
#define Colours_Red     4
#define Colours_Magenta  5
#define Colours_Brown   6
#define Colours_LightGrey  7
#define Colours_DarkGrey  8
#define Colours_LightBlue  9
#define Colours_LightGreen  10
#define Colours_LightCyan  11
#define Colours_LightRed  12
#define Colours_LightMagenta  13
#define Colours_Yellow  14
#define Colours_White   15


#undef vextern

#endif /*ColoursH*/

/* End. */
