/* Header for module Debug, generated by p2c */
#ifndef DebugH
#define DebugH


#ifdef DebugG
# define vextern
#else
# define vextern extern
#endif

/*
    Title      : Debug
    Author     :
    System     : UNIX (gm2)
    Date       : Sat Aug 13 19:41:57 1994
    Last edit  : Sat Aug 13 19:41:57 1994
    Description: provides some simple debugging routines.
*/



/*
   Halt - writes a message in the format:
          Module:Line:Message

          to the debugging device. (Scn.Write).
          It then terminates by looping forever.
*/

extern void Debug_Halt(const int Message_LOW, const int Message_HIGH,
  const Char *Message, unsigned int LineNo, const int Module_LOW,
  const int Module_HIGH, const Char *Module);


/*
   DebugString - writes a string to the debugging device (Scn.Write).
                 It interprets \n as carriage return, linefeed.
*/

extern void Debug_DebugString(const int a_LOW, const int a_HIGH,
			      const Char *a);


#undef vextern

#endif /*DebugH*/

/* End. */
