/* Header for module Exceptions, generated by p2c */
#ifndef ExceptionsH
#define ExceptionsH


#ifdef ExceptionsG
# define vextern
#else
# define vextern extern
#endif

/*
    Title      : Exceptions
    Author     : Gaius Mulley
    System     : RTS (gm2)
    Date       : Thu Aug 11 08:19:21 1994
    Last edit  : Thu Aug 11 08:19:21 1994
    Description: provides a simple? set of 386/486 exception handlers.
*/



/*
   Init - install a set of 386/486 exception handlers.
*/

extern void Exceptions_Init(void);


#undef vextern

#endif /*ExceptionsH*/

/* End. */
