/* Header for module KeyBoardConvert, generated by p2c */
#ifndef KeyBoardConvertH
#define KeyBoardConvertH


#ifndef StdIOH
#include "GStdIO.h"
#endif


#ifdef KeyBoardConvertG
# define vextern
#else
# define vextern extern
#endif



typedef void (*KeyBoardConvert_ConsoleSwitchProc)(unsigned int);



extern void KeyBoardConvert_ScanToASCII(void (*ReadDeliver)(Char), Char ch,
					void (*ConsoleSwitch)(unsigned int));


/*
   SetFunctionString - sets a function key to deliver a string, a,
                       when pressed.
*/

extern void KeyBoardConvert_SetFunctionString(unsigned int Function,
  const int a_LOW, const int a_HIGH, const Char *a);


#undef vextern

#endif /*KeyBoardConvertH*/

/* End. */
