/* Header for module NonAscii, generated by p2c */
#ifndef NonAsciiH
#define NonAsciiH


#ifdef NonAsciiG
# define vextern
#else
# define vextern extern
#endif



#define NonAscii_hm     'G'   /* Home                         */
#define NonAscii_up     'H'   /* Cursor Up                    */
#define NonAscii_puh    'I'   /* Page Up and Home             */
#define NonAscii_lft    'K'   /* Left Cursor                  */
#define NonAscii_rgt    'M'   /* Right Cursor                 */
#define NonAscii_end    'O'   /* End                          */
#define NonAscii_dwn    'P'   /* Cursor Down                  */
#define NonAscii_in     'R'   /* Insert                       */
#define NonAscii_dl     'S'   /* Delete                       */
#define NonAscii_pdh    'Q'   /* Page Down and Home           */
#define NonAscii_bw     's'   /* Backwards a Word             */
#define NonAscii_fw     't'   /* Forwards a Word              */
#define NonAscii_ce     'u'   /* Ctrl End                     */
#define NonAscii_cpd    'v'   /* Ctrl Page Up                 */
#define NonAscii_chm    'w'   /* Ctrl Home                    */
/* p2c: ../luk-1.0/def/NonAscii.def:24: 
 * Note: Character >= 128 encountered [281] */
#define NonAscii_cpu    132   /* Ctrl Page Up                 */


#undef vextern

#endif /*NonAsciiH*/

/* End. */
