/* Header for module NumberIO, generated by p2c */
#ifndef NumberIOH
#define NumberIOH


#ifdef NumberIOG
# define vextern
#else
# define vextern extern
#endif

/*
   Author     : Gaius Mulley
   Date       : '84
   LastEdit   : Thu Nov 23 19:01:25 GMT 2000
   Description: Provides all the input/output of numbers, and also the conversion
                of numbers to strings and visa versa.
*/



extern void NumberIO_ReadCard(unsigned int *x);

extern void NumberIO_WriteCard(unsigned int x, unsigned int n);

extern void NumberIO_ReadHex(unsigned int *x);

extern void NumberIO_WriteHex(unsigned int x, unsigned int n);

extern void NumberIO_ReadInt(int *x);

extern void NumberIO_WriteInt(int x, unsigned int n);

extern void NumberIO_CardToStr(unsigned int x, unsigned int n,
			       const int a_LOW, const int a_HIGH, Char *a);

extern void NumberIO_StrToCard(const int a_LOW, const int a_HIGH,
			       const Char *a, unsigned int *x);

extern void NumberIO_HexToStr(unsigned int x, unsigned int n, const int a_LOW,
			      const int a_HIGH, Char *a);

extern void NumberIO_StrToHex(const int a_LOW, const int a_HIGH,
			      const Char *a, unsigned int *x);

extern void NumberIO_IntToStr(int x, unsigned int n, const int a_LOW,
			      const int a_HIGH, Char *a);

extern void NumberIO_StrToInt(const int a_LOW, const int a_HIGH,
			      const Char *a, int *x);

extern void NumberIO_ReadOct(unsigned int *x);

extern void NumberIO_WriteOct(unsigned int x, unsigned int n);

extern void NumberIO_OctToStr(unsigned int x, unsigned int n, const int a_LOW,
			      const int a_HIGH, Char *a);

extern void NumberIO_StrToOct(const int a_LOW, const int a_HIGH,
			      const Char *a, unsigned int *x);

extern void NumberIO_ReadBin(unsigned int *x);

extern void NumberIO_WriteBin(unsigned int x, unsigned int n);

extern void NumberIO_BinToStr(unsigned int x, unsigned int n, const int a_LOW,
			      const int a_HIGH, Char *a);

extern void NumberIO_StrToBin(const int a_LOW, const int a_HIGH,
			      const Char *a, unsigned int *x);

extern void NumberIO_StrToBinInt(const int a_LOW, const int a_HIGH,
				 const Char *a, int *x);

extern void NumberIO_StrToHexInt(const int a_LOW, const int a_HIGH,
				 const Char *a, int *x);

extern void NumberIO_StrToOctInt(const int a_LOW, const int a_HIGH,
				 const Char *a, int *x);


#undef vextern

#endif /*NumberIOH*/

/* End. */
